import type { Metadata } from 'next';

import { Comfortaa, Open_Sans } from 'next/font/google';
import './globals.css';
import Header from '@/components/header';
import { ThemeProvider } from '@/components/theme-provider';
import NavBar from '@/components/nav-bar';

const comfortaaSans = Comfortaa({
  variable: '--font-comfortaa',
  subsets: ['latin'],
});

const openSans = Open_Sans({
  variable: '--font-openSans',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Dotap',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br" suppressHydrationWarning>
      <body
        className={`${openSans.variable} ${comfortaaSans.variable} antialiased`}
        suppressHydrationWarning
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Header />
          <div className="grid grid-cols-[14rem_1fr] gap-2 h-[calc(100vh-3.6rem)]">
            <NavBar />
            <main className="container m-auto h-full p-4">{children}</main>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
